services:
  app-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: testmarkdb-app
    profiles: ["build"]

  web:
    image: testmarkdb-app
    container_name: web-app
    restart: unless-stopped

    environment:
      - DJANGO_SETTINGS_MODULE=root.settings
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8800:80"
    depends_on:
      - web

  celery:
    image: testmarkdb-app:latest
    container_name: celery-worker
    restart: unless-stopped
    entrypoint: ["celery"]
    working_dir: /app/server
    command: ["-A", "root", "worker", "--loglevel=INFO", "--pool=threads"]    
    environment:
      - DJANGO_SETTINGS_MODULE=root.settings
    depends_on:
      - web
