services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${ACR}/testmarkdb-app
    container_name: web-app
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=root.settings
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ${ACR}/testmarkdb-nginx
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web

  celery:
    image: ${ACR}/testmarkdb-app
    container_name: celery
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=root.settings
    depends_on:
      - web
