services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: testmarkdb-app
    container_name: web-app
    restart: unless-stopped

    environment:
      - DJANGO_SETTINGS_MODULE=root.settings
    expose:
      - "8000"
      
    env_file:
      - ./.env
    volumes:
      - ./server/certs/:/app/server/certs:ro

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8800:80"
    depends_on:
      - web

  celery:
    image: testmarkdb-app
    container_name: celery-worker
    restart: unless-stopped
    entrypoint: ["celery"]
    working_dir: /app/server
    command: ["-A", "root", "worker", "--loglevel=INFO", "--pool=threads"]    
    environment:
      - DJANGO_SETTINGS_MODULE=root.settings
    
    env_file:
      - ./.env
    volumes:
      - ./server/certs/:/app/server/certs:ro

    depends_on:
      - web
