# Generated by Django 5.2.5 on 2025-08-31 00:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('exam_date', models.DateField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Examinee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('salt', models.BinaryField(max_length=32)),
                ('hashed', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ExamineeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examinee')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_paper_code', models.CharField(max_length=6)),
                ('number_of_questions', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamineePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('mark_result', models.BooleanField()),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examinee')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exampaper')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exampaper')),
            ],
        ),
    ]
