# Generated by Django 5.2.5 on 2025-08-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('salt', models.BinaryField(max_length=32)),
                ('hashed', models.CharField(max_length=64)),
            ],
        ),
    ]
