name: Compose Build & Push to ACR

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:
env:
    ACR: ${{ secrets.ACR_LOGIN_SERVER }}
    USERNAME: ${{ secrets.ACR_USERNAME }}
    PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
    build-push:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set up Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to ACR
            uses: docker/login-action@v3
            with:
                registry: ${{ env.ACR }}
                username: ${{ env.USERNAME }}
                password: ${{ env.PASSWORD }}
          - name: Build with Compose
            run: docker compose -f docker-compose.prod.yml build --pull

          - name: Push with Compose
            run: docker compose push