name: Compose Build & Push to ACR

on:
    push:
        branches: 
          - main
    workflow_dispatch:
env:
    ACR: ${{ secrets.ACR_LOGIN_SERVER }}
    USERNAME: ${{ secrets.ACR_USERNAME }}
    PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
    # build-push:
    #     runs-on: ubuntu-latest
    #     permissions:
    #       contents: read #This is required for actions/checkout
    #     steps:
    #       - name: Checkout
    #         uses: actions/checkout@v4

    #       - name: Set up Buildx
    #         uses: docker/setup-buildx-action@v3

    #       - name: Login to ACR
    #         uses: docker/login-action@v3
    #         with:
    #             registry: ${{ env.ACR }}
    #             username: ${{ env.USERNAME }}
    #             password: ${{ env.PASSWORD }}
    #       - name: Build with Compose
    #         run: docker compose -f docker-compose.prod.yml build --pull

    #       - name: Push with Compose
    #         run: docker compose -f docker-compose.prod.yml push

    restart-webapp:
        runs-on: ubuntu-latest
        # needs: build-push
        permissions:
          id-token: write #This is required for requesting the JWT
        steps:
          - name: Login to Azure
            uses: azure/login@v2
            with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          - name: Restart Web App
            run: az webapp restart --name testmarkdb --resource-group testmarkdb
          - name: Restart Celery
            run: az webapp restart --name testmarkdb-celery --resource-group testmarkdb